on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The prerelease tag to apply on the release branch (if any). If not specified, any existing prerelease tag will be removed. The preceding hyphen may be omitted.'
        required: false
        default: ''
      nextVersion:
        description: 'The version to set for the current branch. If omitted, the next version is determined automatically by incrementing the current version.'
        required: false
        default: ''
      versionIncrement:
        type: choice
        options:
        - major
        - minor
        - build
        description: 'Overrides the versionIncrement setting set in version.json for determining the next version of the current branch.The version to set for the current branch. If omitted, the next version is determined automatically by incrementing the current version.'
        required: false
        default: ''

env:
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  prepare-release:
    name: Prepare release
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Setup Nerdbank.GitVersioning
        run: dotnet tool install nbgv --global

      - name: Prepare release
        run: nbgv prepare-release ${{ github.event.inputs.tag }}

      - name: Push commit and new branch
        run: git push --all origin