on:
  push:
    tags:
      - 'release-*'

env:
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    name: Build
    uses: umbraco/UI-Examples/.github/workflows/build.yml@master
    
  publish:
    name: Publish
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages

      - name: Setup UmbPack
        run: dotnet tool install Umbraco.Tools.Packages --global

      - name: Get Umbraco package file name
        id: get_package
        run: echo ::set-output name=PACKAGE::$(Get-Item *.zip | Select-Object -First 1 -ExpandProperty Name)

      - name: Push to Our.Umbraco
        run: umbpack push "${{ steps.get_package.outputs.PACKAGE }}" -k "$env:apiKey" -a *
        env:
          apiKey: ${{ secrets.OURUMBRACO_API_KEY }}

      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key "$env:apiKey" --skip-duplicate
        env:
          apiKey: ${{ secrets.NUGET_API_KEY }}